maxcountryman/flask-seasurf

flask_seasurf.py
An example would be:
`CSRF_COOKIE_DOMAIN='.example.com'`
I think I can write a test for this
`domain=None` by default so this change is backwards compatible.
Closes #51
=> add optional CSRF_COOKIE_DOMAIN setting

flask_seasurf.py, test_seasurf.py
Flask-Seasurf has various issues with unicode URLs due to the incorrect use of `format`.
Patch + tests included
=> Fix problems with unicode URLs

flask_seasurf.py, test_seasurf.py
Some session backends only save the session if it was modified. Flask-Seasurf therefore shouldn't modify the session on every request.
Patch + test included.
=> Don't write session unless it's modified

flask_seasurf.py
Fixes #55.
Raising `Forbidden` exception instead of calling `abort` to set custom csrf error description.
This propagates automatically to Flask's default error handler:
=> better error exception descriptions

docs/index.rst, flask_seasurf.py, test_seasurf.py
Fixes #46.
Adds a new Flask app config `CSRF_CHECK_REFERER` which defaults to `True`.
Adds one new test for `CSRF_CHECK_REFERER` set to `False` to make sure a request succeeds when the Referer header is invalid.
=> option to disable Referer check

flask_seasurf.py
When using the template global function `csrf_token()` with Python3, the token is displayed in your template like `b'abcd'` when it should just be `abcd`. To prevent this, turn the `bytes` token into `str`.
=> prevent Jinja2 from displaying csrf_token() output wrapped with b''

flask_seasurf.py, test_seasurf.py
Adds tests for:
* passing the csrf token in the `X-CSRFToken` header
* passing the csrf token in form encoded data
* prevent hijacking requests with invalid json (in py3 flask returns a 400 response when Flask-SeaSurf accesses `request.json` while it should be up to the user's route function to access the json data or not).
=> improve test coverage and prevent hijacking requests with invalid json

setup.py
Added python 3 classifier to setup.py so that it is not listed as a blocking dependency for python 3 flask applications.
https://caniusepython3.com/project/Flask-SeaSurf
=> Added Python 3 classifier to setup.py

flask_seasurf.py
Fixes #64 
Adds `AttributeError` to the exceptions for trying to read JSON data from the request in `_before_request` in order to support the case where JSON data is solely a list. If the JSON data is a list, we assume that it does not contain the `request_csrf_token` and move forward to look for the token in the headers.
=> Except json.get error for JSON list data

docs/index.rst
I have added the Note section to mention about the TESTING mode. if TESTING = TRUE, then tokens are not generated and SeaSruf silently returns. This will cause tokens to be "None" in the HTML forms.
=> Updated docs to mention about TESTING mode

.travis.yml, flask_seasurf.py, test_seasurf.py
The current behavior of Flask-SeaSurf causes it to send a Set-Cookie header on every request unless the view function is wrapped in `@csrf.exempt` or `SEASURF_INCLUDE_OR_EXEMPT_VIEWS` is set to `include`.
This unfortunately breaks caching. For example, Nginx will not cache requests with the `Vary` or `Set-Cookie` headers. This is bad for frequent AJAX GET requests that have no need of the CSRF Token(as one example).
Django gets around this issue by checking to see if the CSRF Token shows up in the request cookies, and checking to see if a token was requested by the template. If explicitly requested (ie by including `{% csrf_token %}` in the template or the CSRF Token in the cookie does not match (non-existent or invalid), the middleware will add the `Set-Cookie` header.
This pull request …
=> Send Set-Cookie header(much) less often to reduce breaking cache

.travis.yml, flask_seasurf.py, test_seasurf.py
For OAuth requests the client is re-authenticating every request and doesn't need CSRF protection. However, using `@csrf.exempt` is dangerous because we don't want to disable CSRF protection for non-OAuth requests to that view.
This adds the ability to disable/enable CSRF protection and setting the CSRF Token cookie on a per-request basis so the same view can handle both OAuth and regular requests.
=> Ability to disable CSRF for OAuth requests

.travis.yml, flask_seasurf.py, test_seasurf.py
This module is available starting with Python 3.6 and provides
cryptographically strong pseudo-random numbers suitable for secrets/tokens.
* https://docs.python.org/3/library/secrets.html
* https://www.python.org/dev/peps/pep-0506/
=> feat: use PEP 506 secrets module if available

MANIFEST.in
This causes the `LICENSE` file to be included in setuptools distributions and fixes #61.
=> add manifest file to fix #61

docs/index.rst, flask_seasurf.py, test_seasurf.py
Customize SameSite to restricts how cookies are sent with requests from external sites.
reference:  
- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)
- [Security Considerations](http://flask.pocoo.org/docs/1.0/security/#set-cookie-options)
=> allow to customize the cookie samesite

README.markdown
Currently, the URL at the bottom of the main README goes to a link which requires a redirect.
=> Change docs URL to avoid redirect

test_seasurf.py
getCookie method included with many of the test suite classes pulls the first item from the dict returned by parse_cookie(). In versions of Python where the dict is not ordered (<=3.5), this may return the session cookie rather than the CSRF token cookie, causing tests to fail. This change to getCookie ensures that the tests don't rely on parse_cookie returned an ordered dict.
Addresses https://github.com/maxcountryman/flask-seasurf/issues/86
=> Fix getCookie implementation in test classes

flask_seasurf.py, test_seasurf.py
_Note: this is basically the same as #84, but has been updated with the test fix merged in #88._ 
This allows controlling validation() calls without applying `@exempt` decorator to each endpoint. Useful when performing widespread manual validation (eg through a custom view decorator or before_request hook).
Happy to add documentation if this makes sense to merge.
We've been using this in production via our fork, but would like to get back on the published package if possible.
=> Add skip_validation decorator to bypass CSRF validation programatically

flask_seasurf.py, test_seasurf.py
The ability to generate a new CSRF token is needed for web applications in which session state changes.  For instance, when a user logs into a website, we need the ability to generate a new CSRF token.  Otherwise, a potential attacker could ‘seed’ the anti-CSRF string by accessing the website site, not even requiring them to authenticate to it, and taking note of the anti-CSRF string.  The attacker would then be able to target the next user that logs in to the application in a CSRF attack as the anti-CSRF string is known to them.
=> Added the ability to clear the current CSRF token and generate a new one

.travis.yml
Flask no longer supports Python 2.6 and 3.3. Since Flask-SeaSurf depends on Flask, we should also drop support for unsupported Python versions.
=> Drop Python 2.6 and 3.3 support

test_seasurf.py
=> Convert duplicated getCookie methods to helper function

flask_seasurf.py, test_seasurf.py
Bad clients can send Referer header with malformed urls, for ex: port that isn't a number.
This change catches the exception from urllib.parse and results in a 403 error instead of 500 error.
=> Prevent unhandled exception from invalid referer hosts

.github/workflows/publish-release.yml, .gitignore, setup.py
@maxcountryman would this help with #75?
This would trigger and make a release every time a new tag is pushed that have the form of `A.B.C` (`0.2.3` can be force pushed again to trigger.)
I've tried pushing it to test.pypi.org and it looks like this: https://test.pypi.org/project/Flask-SeaSurf-gaborfeher/
The changes in setup.py are because of errors reported by PyPI.
=> Add a GitHub action to push releases to PyPI

docs/index.rst
The only way to tell the default behavior of the extension was to look in the code.
This commit changes the structure of the doc section related to config variables to be presented as a table and to list default values. Some of the missing config variables were added along the way.
=> Update the list of configuration variables

flask_seasurf.py
...instead of `werkzeug.security.safe_str_cmp`, which is [deprecated](https://werkzeug.palletsprojects.com/en/2.0.x/utils/#werkzeug.security.safe_str_cmp) as of Werkzeug 2.0 and emits a DeprecationWarning on usage:
```
flask_seasurf.py:317: DeprecationWarning: 'safe_str_cmp' is deprecated and will be removed in Werkzeug 2.1. Use 'hmac.compare_digest' instead.
if some_none or not safe_str_cmp(request_csrf_token, server_csrf_token):
```
Note that [`hmac.compare_digest`](https://docs.python.org/3/library/hmac.html#hmac.compare_digest) is available in Python 2.7.7+ and Python 3.3+. In order not to make things worse for older Python versions, we fall back to the old behaviour if it is unavailable.
=> Use 'hmac.compare_digest' if available

docs/conf.py
Fixes the error when building docs on RTD:
```
Running Sphinx v1.8.6
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/flask-seasurf/envs/stable/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
execfile_(filename, namespace)
File "/home/docs/checkouts/readthedocs.org/user_builds/flask-seasurf/envs/stable/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
exec_(code, _globals)
File "/home/docs/checkouts/readthedocs.org/user_builds/flask-seasurf/checkouts/stable/docs/conf.py", line 53, in <module>
open(module_path))[0]
TypeError: 'filter' object is not subscriptable
```
=> Fix version parsing in docs

flask_seasurf.py
The return value was opposite what it should be in the docs example.
=> Fix disable_cookie docs example

flask_seasurf.py
When using flask_json you can cause a JsonError to be raised even if you call hasattr(request, 'json') and the request has an empty body
=> Validate the request is actually json

flask_seasurf.py, test_seasurf.py
When a malicious user changes the csrf token value to contain non-ASCII characters, Flask-SeaSurf raises a `TypeError`. This prevents that error by catching and evaluating the strings as not matching.
=> Catch TypeError comparing strings with non-ASCII characters is not supported

test_seasurf.py
This fixes two sets due to `cookie_jar` being removed from the test client in Werkzeug.
Some other tests fail but I am unsure how to fix them.
=> Fix test failures related to Werkzeug updates
